# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/primerParcial/primerParcial.srcs/sources_1/ip/BlockRam0/BlockRam0.xci
# IP: The module: 'BlockRam0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/primerParcial/primerParcial.gen/sources_1/ip/BlockRam0/BlockRam0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/primerParcial/primerParcial.srcs/sources_1/ip/BlockRam0/BlockRam0.xci
# IP: The module: 'BlockRam0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mari-ser/Documents/UTN/Tecnicas Digitales I/agmartinez/primerParcial/primerParcial.gen/sources_1/ip/BlockRam0/BlockRam0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BlockRam0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
